export const ALL_TICKETS = [
  {
    id: 7,
    name: "Ticket7",
    date: "2021-07-30",
    resolutionDate: "2021-08-30",
    urgency: "average",
    status: "submitted",
    category: "securityAndAccess",
    ticketOwner: "Robert Oppenheimer",
    comment: "tl dr",
    description: "",
  },
  {
    id: 8,
    name: "Ticket8",
    date: "2021-08-21",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "submitted",
    category: "hardwareAndSoftware",
    ticketOwner: "Max Plank",
    comment: "tl dr",
    description: "WTF",
  },
  {
    id: 9,
    name: "Ticket9",
    date: "2021-06-21",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "draft",
    category: "applicationAndService",
    ticketOwner: "Ferdinand de Saussure",
    comment: "tl dr",
    description:
      "Structural linguistics is defined as a study of language based on the theory that language is a structured system of formal units such as sentences and syntax. An example of structural linguistics is phonetics",
  },
  {
    id: 0,
    name: "Ticket1",
    date: "2021-07-14",
    resolutionDate: "2021-08-30",
    urgency: "high",
    status: "submitted",
    category: "benefitsAndPaperWork",
    ticketOwner: "Charles Sanders Peirce",
    comment: "",
    description: "",
  },
  {
    id: 1,
    name: "Ticket2",
    date: "2021-07-12",
    resolutionDate: "2021-08-30",
    urgency: "critical",
    status: "submitted",
    category: "workAndFacilities",
    ticketOwner: "Jacques-Marie-Émile Lacan",
    comment: "",
    description: "",
  },
  {
    id: 2,
    name: "Ticket3",
    date: "2021-07-21",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "submitted",
    category: "securityAndAccess",
    ticketOwner: "Jacques Derrida",
    comment: "GG WP",
    description: "",
  },
  {
    id: 3,
    name: "Ticket4",
    date: "2021-10-12",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "draft",
    category: "hardwareAndSoftware",
    ticketOwner: "Umberto Eco",
    comment: "",
    description: "",
  },
  {
    id: 4,
    name: "Ticket5",
    date: "2021-09-12",
    resolutionDate: "2021-08-30",
    urgency: "medium",
    status: "draft",
    category: "workAndFacilities",
    ticketOwner: "Umberto Eco",
    comment: "LOL KEK",
    description:
      "Horror has a face... and you must make a friend of horror. Horror and moral terror are your friends. If they are not, then they are enemies to be feared. They are truly enemies!",
  },
  {
    id: 6,
    name: "Ticket6",
    date: "2021-07-23",
    resolutionDate: "2021-08-30",
    urgency: "high",
    status: "submitted",
    category: "applicationAndService",
    ticketOwner: "Benedetto Croce",
    comment: "LOL KEK",
    description:
      "Horror has a face... and you must make a friend of horror. Horror and moral terror are your friends. If they are not, then they are enemies to be feared. They are truly enemies!",
  },
];

export const MY_TICKETS = [
  {
    id: 0,
    name: "Ticket1",
    date: "2021-07-22",
    resolutionDate: "2021-08-30",
    urgency: "high",
    status: "submitted",
    category: "workAndFacilities",
    ticketOwner: "Benedetto Croce",
    comment: "",
    description: "",
  },
  {
    id: 1,
    name: "Ticket2",
    date: "2021-07-24",
    resolutionDate: "2021-08-30",
    urgency: "critical",
    status: "submitted",
    category: "securityAndAccess",
    ticketOwner: "Umberto Eco",
    comment: "",
    description: "desc",
  },
  {
    id: 2,
    name: "Ticket3",
    date: "2021-07-27",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "submitted",
    category: "securityAndAccess",
    ticketOwner: "Benedetto Croce",
    comment: "tl dr",
    description: "",
  },
  {
    id: 3,
    name: "Ticket4",
    date: "2021-08-12",
    resolutionDate: "2021-08-30",
    urgency: "low",
    status: "draft",
    category: "securityAndAccess",
    ticketOwner: "Анатолий Миценгендлер",
    comment: "GTFO",
    description: "",
  },
  {
    id: 4,
    name: "Ticket5",
    date: "2021-07-22",
    resolutionDate: "2021-08-30",
    urgency: "medium",
    status: "draft",
    category: "applicationAndService",
    ticketOwner: "Jacques Derrida",
    comment: "tl dr",
    description: "GFYS",
  },
];
