export const ALL_TICKETS = [
  {
    id: 7,
    name: "Ticket7",
    date: new Date().toLocaleDateString(),
    urgency: "meduim",
    status: "submitted",
    category: "Security and Access",
    ticketOwner: "Robert Oppenheimer",
  },
  {
    id: 8,
    name: "Ticket8",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "submitted",
    category: "Hardware & Software",
    ticketOwner: "Max Plank",
  },
  {
    id: 9,
    name: "Ticket9",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "draft",
    category: "Application & Service",
    ticketOwner: "Ferdinand de Saussure",
  },
  {
    id: 0,
    name: "Ticket1",
    date: new Date().toLocaleDateString(),
    urgency: "high",
    status: "submitted",
    category: "Benefits & Paper Work",
    ticketOwner: "Charles Sanders Peirce",
  },
  {
    id: 1,
    name: "Ticket2",
    date: new Date().toLocaleDateString(),
    urgency: "meduim",
    status: "submitted",
    category: "Workplaces & Facilities",
    ticketOwner: "Jacques-Marie-Émile Lacan",
  },
  {
    id: 2,
    name: "Ticket3",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "submitted",
    category: "Security & Access",
    ticketOwner: "Jacques Derrida",
  },
  {
    id: 3,
    name: "Ticket4",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "draft",
    category: "Hardware & Software",
    ticketOwner: "Umberto Eco",
  },
  {
    id: 4,
    name: "Ticket5",
    date: new Date().toLocaleDateString(),
    urgency: "medium",
    status: "draft",
    category: "Workplaces & Facilities",
    ticketOwner: "Umberto Eco",
  },
  {
    id: 6,
    name: "Ticket6",
    date: new Date().toLocaleDateString(),
    urgency: "high",
    status: "submitted",
    category: "Application & Service",
    ticketOwner: "Benedetto Croce",
  },
];

export const MY_TICKETS = [
  {
    id: 0,
    name: "Ticket1",
    date: new Date().toLocaleDateString(),
    urgency: "high",
    status: "submitted",
    category: "Workplaces & Facilities",
    ticketOwner: "Benedetto Croce",
  },
  {
    id: 1,
    name: "Ticket2",
    date: new Date().toLocaleDateString(),
    urgency: "meduim",
    status: "submitted",
    category: "Security & Access",
    ticketOwner: "Umberto Eco",
  },
  {
    id: 2,
    name: "Ticket3",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "submitted",
    category: "Security & Access",
    ticketOwner: "Benedetto Croce",
  },
  {
    id: 3,
    name: "Ticket4",
    date: new Date().toLocaleDateString(),
    urgency: "low",
    status: "draft",
    category: "Security and Access",
    ticketOwner: "Анатолий Миценгендлер",
  },
  {
    id: 4,
    name: "Ticket5",
    date: new Date().toLocaleDateString(),
    urgency: "medium",
    status: "draft",
    category: "Application & Service",
    ticketOwner: "Jacques Derrida",
  },
];
